services:
  - type: web
    name: eld-log-frontend
    plan: free
    runtime: node
    buildCommand: npm ci && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://eld-log-api.onrender.com/api
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080 